@baseUrl = http://localhost:3000/api/v2/
@AuthToken = {{AuthSignInPost.response.body.access_token}}

### Player

# @name PlayerGetAll
GET {{baseUrl}}player
?limit=15
&offset=0

###
# @name PlayerGetOne
GET {{baseUrl}}player/69bab231384cfd6900e2e1a9

###
# @name PlayerPost
POST {{baseUrl}}player
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "name": "Gustavo Cruz",
  "ranking": "A",
  "positionRanking": 1,
  "pictureUrl": ""
}

###
# @name PlayerPatch
PATCH  {{baseUrl}}player/69b1929bf60852e6e5bc7a1
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "name": "test updated"
}
###
# @name PlayerDelete
DELETE  {{baseUrl}}player/69ab34d55a827cb4bdbe175e
Authorization: Bearer {{AuthToken}}

###
# @name UploadedImagePlayerPost
PATCH  {{baseUrl}}player/69b1b16280a6ed3deee3979e/upload-image
Authorization: Bearer {{AuthToken}}
Content-Type: multipart/form-data; boundary=----FormBoundary

------FormBoundary
Content-Disposition: form-data; name="file"; filename="nestjs.png"
Content-Type: image/png

< ./dev/nestjs.png 
------FormBoundary--


###
### Category
###

# @name CategoryGetAll
GET {{baseUrl}}category
Authorization: Bearer {{AuthToken}}

###
# @name CategoryGetOne
GET {{baseUrl}}category/69bab2fb384cfd6900e2e1b1
Authorization: Bearer {{AuthToken}}

###
# @name CategoryPost
POST {{baseUrl}}category
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "name": "C",
  "description": "any desripition",
  "events": []
}

###
# @name CategoryPatch
PATCH  {{baseUrl}}category/69bab2fb384cfd6900e2e1b1
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "addEvents": [
    {
			"name": "VICTORY",
			"operation": "+",
			"value": 10
		},
		{
			"name": "VICTORY_LEADER",
			"operation": "+",
			"value": 20
		},
		{
			"name": "DEFEAT",
			"operation": "-",
			"value": 5
		}
  ],
  "removeEvents": [
    {
      "name": "one event",
      "operation": "any operation"
    }
  ]
}
###
# @name CategoryDelete
DELETE  {{baseUrl}}category/69af0f57338b6c3df97ea22f
Authorization: Bearer {{AuthToken}}

###
# @name AddPlayer
PATCH  {{baseUrl}}category/69bab2fb384cfd6900e2e1b1/addPlayer
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "addPlayers": ["69bab231384cfd6900e2e1a9"]
}

###
# @name RemovePlayer
PATCH  {{baseUrl}}category/69bab2ef384cfd6900e2e1af/removePlayer
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "removePlayers": ["69bab231384cfd6900e2e1a9"]
}


###
### challenge
###

# @name ChallengeGetAll
GET {{baseUrl}}challenge
?limit=10
&offset=0

###
# @name ChallengeGetOne
GET {{baseUrl}}challenge/69bd997c79a8771c24c56f39
Authorization: Bearer {{AuthToken}}

###
# @name ChallengePost
POST {{baseUrl}}challenge
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "dateHourChallenge": "2026-03-20T07:30:00",
  "applicant": "69bab231384cfd6900e2e1a9",
  "players": ["69bab231384cfd6900e2e1a9", "69bf5893f22d968dc1f14f80"]
}

###
# @name ChallengePatch
PATCH  {{baseUrl}}challenge/69bd997c79a8771c24c56f39
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "status": "ACCEPTED"
}

###
# @name ChallengeDelete
DELETE  {{baseUrl}}challenge/69bd941866036a7794d865de
Authorization: Bearer {{AuthToken}}

###
# @name ChallengePlayerGetOne
GET {{baseUrl}}challenge/player/69bab21c384cfd6900e2e1a7
Authorization: Bearer {{AuthToken}}

###
# @name ChallengeAddMatch
PATCH  {{baseUrl}}challenge/69bd997c79a8771c24c56f39/AddMatch
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "result": [
    {
    "setMacth": "3-0"
    },
    {
    "setMacth": "3-1"
    }
  ],
  "def": "69bab231384cfd6900e2e1a9"
}


###
### Match
###

# @name MatchGetAll
GET {{baseUrl}}match
?limit=1
&offset=0
Authorization: Bearer {{AuthToken}}

###
# @name MatchGetOne
GET {{baseUrl}}match/69bca0c9c2b417030bb416b3
Authorization: Bearer {{AuthToken}}

###
# # @name MatchPost
# POST {{baseUrl}}match
# Content-Type: application/json
# Authorization: Bearer {{AuthToken}}

# {
#   "challenge": "69b879414a0cd4f77edb80ec",
#   "category": "69bab2fb384cfd6900e2e1b1",
#   "players": ["69a1a8f29fda1c56f912a825", "69a6f7a2f38dbedaa8bc29c5"],
#   "result": [
#     {
#       "setMacth": "2-0"
#     }
#   ],
#   "def": "69a1a8f29fda1c56f912a825"
# }

# ###
# # @name MatchPatch
# PATCH  {{baseUrl}}match/69b89d2bbacb176f5e3c43ec
# Content-Type: application/json
# Authorization: Bearer {{AuthToken}}

# {
#   "result": [
#     {
#     "setMacth": "3-1"
#     }
#   ],
#   "def": "69a1a8f29fda1c56f912a826"
# }

# ###
# # @name MatchDelete
# DELETE  {{baseUrl}}match/69bac6486a9145e9d4b1753b
# Authorization: Bearer {{AuthToken}}


###
### Ranking
###

# ###
# # @name RankingPost
# POST {{baseUrl}}ranking
# Content-Type: application/json
# Authorization: Bearer {{AuthToken}}

# {
#   "players": ["69a1a8f29fda1c56f912a825", "69a6f7a2f38dbedaa8bc29c5"]
# }

###
# @name RankingGetAll
GET {{baseUrl}}ranking
?limit=1
&offset=0

###
# @name RankingGetFindOneById
GET {{baseUrl}}ranking/69bc3c5a62cb7df5b0d5aa07
?limit=1
&offset=0

# ###
# # @name RankingPatch
# PATCH  {{baseUrl}}ranking/69bc3c5a62cb7df5b0d5aa07
# Content-Type: application/json
# Authorization: Bearer {{AuthToken}}

# {
#   "position": 1,
#   "score": 10,
#   "matchHistory": {
#     "victory": 1,
#     "defeat": 0
#   }
# }

# ###
# # @name RankingDelete
# DELETE  {{baseUrl}}ranking/69bd682096890a41b81fb1d1
# Authorization: Bearer {{AuthToken}}

# ###
# # @name RankingModifyPerMatchPost
# POST {{baseUrl}}ranking/Modify-per-match
# Content-Type: application/json
# Authorization: Bearer {{AuthToken}}

# {
#   "category": "69bab2fb384cfd6900e2e1b1",
#   "players": ["69a1a8f29fda1c56f912a825", "69a6f7a2f38dbedaa8bc29c5"],
#   "def": "69a6f7a2f38dbedaa8bc29c5"
# }


### Auth

###
# @name AuthSignUpPost
POST {{baseUrl}}auth/signUp
Content-Type: application/json

{
  "email": "gustavo.cruzs.dev@gmail.com",
  "password": "Gu$tavo123"
}

###
# @name AuthSignInPost
POST {{baseUrl}}auth/signIn
Content-Type: application/json

{
  "email": "gustavo.cruzs.dev@gmail.com",
  "password": "Gu$tavo123"
}
