@baseUrl = http://localhost:3000/api/v1/

### Player

# @name PlayerGetAll
GET {{baseUrl}}player
?limit=15
&offset=0

###
# @name PlayerGetOne
GET {{baseUrl}}player/69b1b16280a6ed3deee3979e

###
# @name PlayerPost
POST {{baseUrl}}player
Content-Type: application/json

{
  "name": "Test",
  "email": "tes@gmail.com",
  "tell": "967734857234",
  "ranking": "A",
  "positionRanking": 1,
  "pictureUrl": ""
}

###
# @name PlayerPatch
PATCH  {{baseUrl}}player/69b1929bf60852e6e5bc7a1
Content-Type: application/json

{
  "name": "test updated"
}
###
# @name PlayerDelete
DELETE  {{baseUrl}}player/69ab34d55a827cb4bdbe175e

###
# @name UploadedImagePlayerPost
PATCH  {{baseUrl}}player/69b1b16280a6ed3deee3979e/upload-image
Content-Type: multipart/form-data; boundary=----FormBoundary

------FormBoundary
Content-Disposition: form-data; name="file"; filename="nestjs.png"
Content-Type: image/png

< ./dev/nestjs.png 
------FormBoundary--

### Category

# @name CategoryGetAll
GET {{baseUrl}}category

###
# @name CategoryGetOne
GET {{baseUrl}}category/69b08073d0b06a83c9e8fe78

###
# @name CategoryPost
POST {{baseUrl}}category
Content-Type: application/json

{
  "name": "AAA",
  "description": "any desripition",
  "events": [
    {
      "name": "Event one",
      "operation": "any operation",
      "value": 50
    },
    {
      "name": "Event two",
      "operation": "any operation",
      "value": 25
    }
  ]

}

###
# @name CategoryPatch
PATCH  {{baseUrl}}category/69af0f57338b6c3df97ea22f
Content-Type: application/json

{
  "name": "b updated",
  "addEvents": [
    {
      "name": "Event four",
      "operation": "any operation",
      "value": 100
    }
  ],
  "removeEvents": [
    {
      "name": "Event one",
      "operation": "any operation"
    }
  ]
}
###
# @name CategoryDelete
DELETE  {{baseUrl}}category/69af0f57338b6c3df97ea22f

###
# @name AddPlayer
PATCH  {{baseUrl}}category/69b08073d0b06a83c9e8fe78/addPlayer
Content-Type: application/json

{
  "addPlayers": ["69b1b16280a6ed3deee3979e", "69b19ee9bee6d74ead12d132", "69b1a808d9215a0b0ece5191"]
}

###
# @name RemovePlayer
PATCH  {{baseUrl}}category/69b08073d0b06a83c9e8fe78/removePlayer
Content-Type: application/json

{
  "removePlayers": ["69b1a808d9215a0b0ece5191"]
}

### challenge

# @name ChallengeGetAll
GET {{baseUrl}}challenge
?limit=10
&offset=0

###
# @name ChallengeGetOne
GET {{baseUrl}}challenge/69b832a91053bde0e1abe28f

###
# @name ChallengePost
POST {{baseUrl}}challenge
Content-Type: application/json

{
  "dateHourChallenge": "2026-03-20T07:30:00",
  "applicant": "69b1b16280a6ed3deee3979e",
  "players": ["69b1b16280a6ed3deee3979e", "69b19ee9bee6d74ead12d132"]
}

###
# @name ChallengePatch
PATCH  {{baseUrl}}challenge/69b70985e4ad71e18c0b04f8
Content-Type: application/json

{
  "dateHourResponse": "2026-03-20T10:30:00",
  "status": "ACCEPTED"
}

###
# @name ChallengeDelete
DELETE  {{baseUrl}}challenge/69b83a772861647287092946

###
# @name ChallengePlayerGetOne
GET {{baseUrl}}challenge/player/69b1b16280a6ed3deee3979e

###
# @name ChallengeAddMatch
PATCH  {{baseUrl}}challenge/69b832731053bde0e1abe28c/AddMatch
Content-Type: application/json

{
  "result": [
    {
    "set": "1-0"
    }
  ],
  "def": "69b1b16280a6ed3deee3979e"
}

### Match

# @name MatchGetAll
GET {{baseUrl}}match
?limit=1
&offset=0

###
# @name MatchGetOne
GET {{baseUrl}}match/69b8815a3e944bae1247165f

###
# @name MatchPost
POST {{baseUrl}}match
Content-Type: application/json

{
  "challenge": "69b879414a0cd4f77edb80ec",
  "category": "any category",
  "players": ["69a1a8f29fda1c56f912a825", "69a6f7a2f38dbedaa8bc29c5"],
  "result": [
    {
    "set": "2-0"
    }
  ],
  "def": "69a1a8f29fda1c56f912a825"
}

###
# @name MatchPatch
PATCH  {{baseUrl}}match/69a99767a689f289aa0f25e7
Content-Type: application/json

{
  "result": [
    {
    "set": "69a1a8f29fda1c56f912a825"
    }
  ],
  "def": "69a1a8f29fda1c56f912a825"
}

###
# @name MatchDelete
DELETE  {{baseUrl}}match/69a9a470288657000ba71f74

