version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    restart: always
    ports:
      - "5672:5672"   # Porta AMQP (Microserviços)
      - "15672:15672" # Porta Dashboard (Navegador)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-local
    restart: always
    ports:
      - "8080:3000" # Exemplo: Acessar via http://localhost:8080
    env_file:
      - ./api-gateway/.env
    depends_on:
      - rabbitmq

  micro-admin-backend:
    build:
      context: ./micro-admin-backend
      dockerfile: Dockerfile
    container_name: micro-admin-backend-local
    restart: always
    env_file:
      - ./micro-admin-backend/.env
    depends_on:
      - rabbitmq

  micro-challenge:
    build:
      context: ./micro-challenge
      dockerfile: Dockerfile
    container_name: micro-challenge-local
    restart: always
    env_file:
      - ./micro-challenge/.env
    depends_on:
      - rabbitmq

  micro-match:
    build:
      context: ./micro-match
      dockerfile: Dockerfile
    container_name: micro-match-local
    restart: always
    env_file:
      - ./micro-match/.env
    depends_on:
      - rabbitmq

  micro-ranking:
    build:
      context: ./micro-ranking
      dockerfile: Dockerfile
    container_name: micro-ranking-local
    restart: always
    env_file:
      - ./micro-ranking/.env
    depends_on:
      - rabbitmq

  micro-send-email:
    build:
      context: ./micro-send-email
      dockerfile: Dockerfile
    container_name: micro-send-email-local
    restart: always
    env_file:
      - ./micro-send-email/.env
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: